[package]
name = "ipld"
version = "0.0.3"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
description = "IPLD types and interfaces"
license = "MIT or Apache-2.0"
edition = "2018"

[lib]
name = "ipld"
path = "src/lib.rs"

[dependencies]
# anyhow = "1.0"
async-trait = "0.1"
cid = "0.3.2"
delegate = { version = "0.4", optional = true }
ipld-macros = { path = "./macros" }
multibase = "0.8"
multihash = "0.10"
serde = { version = "1.0" }
serde_cbor = { version = "0.11", optional = true }
serde_json = { version = "1.0", optional = true }
serde_repr = "0.1"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"
proptest = "0.9"

[features]
default = []
dag-cbor = ["serde_cbor", "serde_cbor/tags"]
dag-json = ["delegate", "serde_json"]
multicodec = ["dag-cbor", "dag-json"]

[workspace]
members = [
  "macros",
  "macros-internals"
]
