[package]
name = "ipld"
version = "0.0.2"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
description = "IPLD types and interfaces"
license = "ISC"
edition = "2018"

[lib]
name = "ipld"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
cid = { version = "^0.3", git = "https://github.com/datalove-app/rust-cid", branch = "cli" }
failure = "0.1"
multibase = "0.7"
multihash = "0.9"
serde = { version = "^1.0" }

[features]
default = []

[workspace]
members = [
  "dag-cbor",
  "dag-json",
  "schema",
  "schema-derive"
]

[patch.crates-io]
