[package]
name = "ipld"
version = "0.1.0"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
description = "Types, traits and macros for the IPLD Data Model, Schema, Representation, and Selector specifications."
license = "MIT or Apache-2.0"
edition = "2018"

[lib]
name = "ipld"
path = "src/lib.rs"

[dependencies]
# core
bytes = "0.5"
cid = "0.3.2"
ipld-macros = { path = "./macros" }
ipld-macros-internals = { path = "./macros-internals" }
multibase = "0.8"
multihash = "0.10"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_repr = "0.1"
# formats
serde_cbor = { version = "0.11", optional = true }
serde_json = { version = "1.0", optional = true }
simd-json = { version = "^0.3", optional = true }
# misc
anyhow = "1.0"
async-stream = "^0.2"
async-trait = "0.1"
delegate = { version = "0.4", optional = true }
downcast-rs = "1.1"
futures = "^0.3"
pin-utils = "0.1.0-alpha.4"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.3"
proptest = "0.9"

[features]
default = ["multicodec"]
dag-cbor = ["serde_cbor/tags"]
dag-json = ["delegate", "serde_json"]
# enables all available multicodecs
multicodec = ["dag-cbor", "dag-json"]
# enables simd-related implementations, including an alternate dag-json
# simd = ["simd-json"]

[workspace]
members = [
  "macros",
  "macros-hack",
  "macros-internals"
]
