[package]
name = "ipld-macros"
version = "0.0.3"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
ipld-macros-internals = { path = "../macros-internals" }
quote = "1.0"
syn = "1.0"

[features]
default = []
